Sprint5 maincontainer
Fullstack-Roligheter/Frontend pull request #30
Opened 2022-04-05 09:16 UTC by CanoodlingSocks

- Kopplat på 5 knappar på Navbaren varav Item-4 är en placeholder och det är fritt fram att ändra den

-- All data (app) renderas inuti main-container
- Index.css har blivit uppdelad i olika stycken beroende på relevans. Här finns css för dom append:ade elementen som skapades upp i ListAllExpensesInBudget.js

- Slopade idéen för sidebar men utkommenterad kod för en sidebar button finns kvar i ListAllExpensesInBudget.js, var snäll och ha kvar den utkommenterade koden

Mvh Daniela
----
"Kachow!" - Blixten McQueen

2022-04-05 09:34 UTC, EmilJohansson90 requested changes
Merge into dev instead of main.

2022-04-05 09:44 UTC, Bergewing reviewed
Isn't this in direct merge conflict with the new navbar system in header and the accompanied code?

2022-04-05 10:33 UTC, Krezeb approved these changes
Kanske blir fel i footer vid CSS overrides med Inline vs Stylesheets. Har justerat lite och löst lite conflicts. Vi testar med det. Kan lösa ev. buggar imorgon.

2022-04-05 10:34 UTC, Saru444 approved these changes
ser bra ut

2022-04-06 11:11 UTC, EmilJohansson90 approved these changes

2022-04-06 11:18 UTC, merged